In [ ]:
#!/usr/bin/env python3 and import pandas and numpy
import pandas as pd
import numpy as np

In [ ]:
# Load the dataset

path = "D:/Learning/IITM/Week3/anime_data.csv"
data = pd.read_csv(path)

In [ ]:
# data
data

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
0,Fullmetal Alchemist: Brotherhood,The foundation of alchemy is based on the law ...,TV,64,NaN,False,Spring,1,Bones,0,...,0,0,0,0,0,0,0,0,0,0
1,your name.,Mitsuha and Taki are two total strangers livin...,Movie,1,107.0,False,is_missing,0,Others,0,...,1,0,0,0,0,0,0,0,0,0
2,A Silent Voice,"After transferring into a new school, a deaf g...",Movie,1,130.0,False,is_missing,0,Kyoto Animation,0,...,0,0,0,0,0,0,0,0,0,0
3,Haikyuu!! Karasuno High School vs Shiratorizaw...,"Picking up where the second season ended, the ...",TV,10,NaN,False,Fall,0,Production I.G,0,...,0,0,0,0,0,0,0,0,0,0
4,Attack on Titan 3rd Season: Part II,The battle to retake Wall Maria begins now! Wi...,TV,10,NaN,False,Spring,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12096,Sore Ike! Anpanman: Kirameke! Ice no Kuni no V...,Princess Vanilla is a princess in a land of ic...,Movie,1,NaN,False,is_missing,0,TMS Entertainment,0,...,0,0,0,0,0,0,0,0,0,0
12097,Hulaing Babies Petit,NaN,TV,12,5.0,False,Winter,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
12098,Marco & The Galaxy Dragon,NaN,OVA,1,NaN,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12099,Xing Chen Bian 2nd Season,Second season of Xing Chen Bian.,Web,3,24.0,True,is_missing,0,is_missing,0,...,0,0,0,0,0,0,1,0,0,0
12100,Ultra B: Black Hole kara no Dokusaisha BB!!,NaN,Movie,1,20.0,False,is_missing,0,Shin-Ei Animation,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# validate null values
data.isnull().sum()

title                            0
description                   4468
mediaType                        0
eps                              0
duration                      4636
ongoing                          0
sznOfRelease                     0
years_running                    0
studio_primary                   0
studios_colab                    0
contentWarn                      0
watched                          0
watching                         0
wantWatch                        0
dropped                          0
rating                           0
votes                            0
tag_Based_on_a_Manga             0
tag_Comedy                       0
tag_Action                       0
tag_Fantasy                      0
tag_Sci_Fi                       0
tag_Shounen                      0
tag_Original_Work                0
tag_Non_Human_Protagonists       0
tag_Drama                        0
tag_Adventure                    0
tag_Family_Friendly              0
tag_Short_Episodes               0
tag_School_Life                  0
tag_Romance                      0
tag_Shorts                       0
tag_Slice_of_Life                0
tag_Seinen                       0
tag_Supernatural                 0
tag_Magic                        0
tag_Animal_Protagonists          0
tag_Ecchi                        0
tag_Mecha                        0
tag_Based_on_a_Light_Novel       0
tag_CG_Animation                 0
tag_Superpowers                  0
tag_Others                       0
tag_missing                      0
dtype: int64

In [ ]:
# data types value counts
data.dtypes.value_counts

<bound method IndexOpsMixin.value_counts of title                             str
description                       str
mediaType                         str
eps                             int64
duration                      float64
ongoing                          bool
sznOfRelease                      str
years_running                   int64
studio_primary                    str
studios_colab                   int64
contentWarn                     int64
watched                       float64
watching                        int64
wantWatch                       int64
dropped                         int64
rating                        float64
votes                           int64
tag_Based_on_a_Manga            int64
tag_Comedy                      int64
tag_Action                      int64
tag_Fantasy                     int64
tag_Sci_Fi                      int64
tag_Shounen                     int64
tag_Original_Work               int64
tag_Non_Human_Protagonists      int64
tag_Drama                       int64
tag_Adventure                   int64
tag_Family_Friendly             int64
tag_Short_Episodes              int64
tag_School_Life                 int64
tag_Romance                     int64
tag_Shorts                      int64
tag_Slice_of_Life               int64
tag_Seinen                      int64
tag_Supernatural                int64
tag_Magic                       int64
tag_Animal_Protagonists         int64
tag_Ecchi                       int64
tag_Mecha                       int64
tag_Based_on_a_Light_Novel      int64
tag_CG_Animation                int64
tag_Superpowers                 int64
tag_Others                      int64
tag_missing                     int64
dtype: object>

In [16]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
eps,12101.0,13.393356,57.925097,1.000,1.000,2.000,12.000,2527.000
duration,7465.0,24.230141,31.468171,1.000,4.000,8.000,30.000,163.000
years_running,12101.0,0.283200,1.152234,0.000,0.000,0.000,0.000,51.000
studios_colab,12101.0,0.051649,0.221326,0.000,0.000,0.000,0.000,1.000
contentWarn,12101.0,0.115362,0.319472,0.000,0.000,0.000,0.000,1.000
watched,12101.0,2862.605694,7724.347024,0.000,55.000,341.000,2026.000,161567.000
watching,12101.0,256.334435,1380.840902,0.000,2.000,14.000,100.000,74537.000
wantWatch,12101.0,1203.681431,2294.327380,0.000,49.000,296.000,1275.000,28541.000
dropped,12101.0,151.568383,493.931710,0.000,3.000,12.000,65.000,19481.000
rating,12101.0,2.949037,0.827385,0.844,2.304,2.965,3.616,4.702
votes,12101.0,2088.124700,5950.332228,10.000,34.000,219.000,1414.000,131067.000
tag_Based_on_a_Manga,12101.0,0.290802,0.454151,0.000,0.000,0.000,1.000,1.000
tag_Comedy,12101.0,0.272870,0.445453,0.000,0.000,0.000,1.000,1.000
tag_Action,12101.0,0.231221,0.421631,0.000,0.000,0.000,0.000,1.000
tag_Fantasy,12101.0,0.181555,0.385493,0.000,0.000,0.000,0.000,1.000
tag_Sci_Fi,12101.0,0.166267,0.372336,0.000,0.000,0.000,0.000,1.000
tag_Shounen,12101.0,0.144864,0.351978,0.000,0.000,0.000,0.000,1.000
tag_Original_Work,12101.0,0.135195,0.341946,0.000,0.000,0.000,0.000,1.000
tag_Non_Human_Protagonists,12101.0,0.112470,0.315957,0.000,0.000,0.000,0.000,1.000
tag_Drama,12101.0,0.106107,0.307987,0.000,0.000,0.000,0.000,1.000
tag_Adventure,12101.0,0.103793,0.305005,0.000,0.000,0.000,0.000,1.000
tag_Family_Friendly,12101.0,0.097017,0.295993,0.000,0.000,0.000,0.000,1.000
tag_Short_Episodes,12101.0,0.096934,0.295880,0.000,0.000,0.000,0.000,1.000
tag_School_Life,12101.0,0.092306,0.289470,0.000,0.000,0.000,0.000,1.000
tag_Romance,12101.0,0.092141,0.289237,0.000,0.000,0.000,0.000,1.000
tag_Shorts,12101.0,0.089662,0.285709,0.000,0.000,0.000,0.000,1.000
tag_Slice_of_Life,12101.0,0.080820,0.272569,0.000,0.000,0.000,0.000,1.000
tag_Seinen,12101.0,0.077101,0.266763,0.000,0.000,0.000,0.000,1.000
tag_Supernatural,12101.0,0.070903,0.256674,0.000,0.000,0.000,0.000,1.000
tag_Magic,12101.0,0.064292,0.245283,0.000,0.000,0.000,0.000,1.000
tag_Animal_Protagonists,12101.0,0.060326,0.238099,0.000,0.000,0.000,0.000,1.000
tag_Ecchi,12101.0,0.057433,0.232678,0.000,0.000,0.000,0.000,1.000
tag_Mecha,12101.0,0.054541,0.227091,0.000,0.000,0.000,0.000,1.000
tag_Based_on_a_Light_Novel,12101.0,0.053384,0.224807,0.000,0.000,0.000,0.000,1.000
tag_CG_Animation,12101.0,0.050079,0.218116,0.000,0.000,0.000,0.000,1.000
tag_Superpowers,12101.0,0.044624,0.206486,0.000,0.000,0.000,0.000,1.000
tag_Others,12101.0,0.090654,0.287128,0.000,0.000,0.000,0.000,1.000
tag_missing,12101.0,0.025866,0.158741,0.000,0.000,0.000,0.000,1.000

In [19]:
#fetch titile where no of eps ==1
data[data['eps']==1]['title'].tolist()

['your name.',
 'A Silent Voice',
 'Gintama Kanketsu-hen: Yorozuya yo Eien Nare',
 'Spirited Away',
 'Wolf Children',
 'Rascal Does Not Dream of a Dreaming Girl',
 "Howl's Moving Castle",
 'Kizumonogatari Movie 3: Reiketsu',
 'Princess Mononoke',
 'Weathering With You',
 'Luo Xiao Hei Zhan Ji Movie',
 'KonoSuba – God’s blessing on this wonderful world! Movie: Legend of Crimson',
 'Mushishi Zoku Shou: Suzu no Shizuku',
 'Mushishi: Hihamukage',
 'The Disappearance of Haruhi Suzumiya',
 'The Garden of Sinners Movie 5: Paradox Paradigm',
 'I Want to Eat Your Pancreas',
 'Hotarubi no Mori e',
 'Mushishi Zoku Shou: Odoro no Michi',
 'Kizumonogatari Movie 2: Nekketsu',
 'Violet Evergarden: Eternity and the Auto Memory Doll',
 "Natsume's Book of Friends Movie: Ephemeral Bond",
 'Youjo Senki: Saga of Tanya the Evil Movie',
 'Steins;Gate Movie: Load Region of Deja Vu',
 'The Boy and the Beast',
 'Made in Abyss Movie: Dawn of the Deep Soul',
 'The Garden of Sinners Movie 7: ......Not Nothing Heart. (Murder Speculation Part B)',
 "Fate/stay night: Heaven's Feel II. lost butterfly",
 'Gintama: Shinyaku Benizakura-hen',
 'My Hero Academia Movie 2: Heroes:Rising',
 'No Game No Life: Zero',
 'Legend of the Galactic Heroes: Die Neue These Second 3',
 'Steins;Gate: Egoistic Poriomania',
 'Black Butler: Book of the Atlantic',
 'Haikyuu!! Tokushuu! Harukou Volley ni Kaketa Seishun',
 'The Disastrous Life of Saiki K. 3',
 'Evangelion: 2.0 You Can (Not) Advance',
 'One Piece Movie 10: Strong World',
 'Hajime no Ippo: Champion Road',
 'Natsume Yuujinchou: Itsuka Yuki no Hi ni',
 'Maquia - When the Promised Flower Blooms',
 'Zoku Owarimonogatari',
 'Nausicaa of the Valley of the Wind',
 'Quan Zhi Gao Shou Movie: For the Glory',
 'My Neighbor Totoro',
 'Grave of the Fireflies',
 'Doukyuusei',
 'The Girl Who Leapt Through Time',
 'Sword of the Stranger',
 'Tengen Toppa Gurren Lagann: Lagann-hen',
 'Violet Evergarden Special',
 'Sora no Aosa wo Shiru Hito yo',
 'One Piece Movie 14: Stampede',
 'Summer Wars',
 'Cowboy Bebop: The Movie',
 'Dragon Ball Super Movie: Broly',
 'Kishibe Rohan wa Ugokanai: The Run',
 'Kizumonogatari Movie 1: Tekketsu',
 'Gintama: Shinyaku Benizakura-hen Special',
 "Kuroko's Basketball: Last Game",
 'Legend of the Galactic Heroes: Die Neue These Second 2',
 'Kamisama Kiss: Kamisama, Shiawase ni Naru',
 'Time of Eve Movie',
 'K-On! Movie',
 'One Piece Film: Z',
 "Kuroko's Basketball: The Greatest Present",
 'My Hero Academia The Movie: Two Heroes',
 'Haikyuu!! Movie 4: Battle of Concepts',
 'Detective Conan: Episode One - The Great Detective Turned Small',
 'Detective Conan Movie 20: The Darkest Nightmare',
 'Puella Magi Madoka Magica the Movie Part 2: Eternal',
 "Fate/stay night: Heaven's Feel I. presage flower",
 'Shelter',
 'Berserk: Golden Age Arc III - The Advent',
 'In This Corner of the World',
 'Tokyo Godfathers',
 'Gintama: Jump Festa 2008',
 'Hajime no Ippo: Mashiba vs Kimura',
 'Oshie to Tabi Suru Otoko',
 'Detective Conan Movie 14: The Lost Ship in the Sky',
 'Haikyuu!! Movie 3: Talent and Sense',
 'Omae Umasou da na Movie',
 'Puella Magi Madoka Magica the Movie Part 3: Rebellion',
 'Psycho-Pass 3: First Inspector',
 'Girls und Panzer der Film',
 'Code Geass Movie: Lelouch of the Re;surrection',
 'Redline',
 'Detective Conan Movie 6: The Phantom of Baker Street',
 'Patema Inverted',
 'Made in Abyss: Hourou Suru Tasogare',
 'Trigun: Badlands Rumble',
 'Whisper of the Heart',
 'The Garden of Sinners Movie 3: Ever Cry, Never Life. (Remaining Sense of Pain)',
 'The House of Small Cubes',
 'Gintama: Jump Festa 2014',
 'Laputa: Castle in the Sky',
 'When Marnie Was There',
 'Fate/stay night: Unlimited Blade Works Prologue',
 'Working!!! Lord of the Takanashi',
 'Ghost in the Shell: Stand Alone Complex - Solid State Society',
 'Promare',
 "Beyond the Boundary Movie: I'll Be Here - Future",
 'Detective Conan Movie 15: Quarter of Silence',
 'Detective Conan Movie 13: The Raven Chaser',
 'Ghost in the Shell: Stand Alone Complex - The Laughing Man',
 'Detective Conan Movie 18: The Sniper From Another Dimension',
 "Kiki's Delivery Service",
 'Code Geass: Lelouch of the Rebellion III - Glorification',
 'Love, Chunibyo & Other Delusions! Movie: Take On Me',
 'Millennium Actress',
 'Berserk: Golden Age Arc II - The Battle for Doldrey',
 'Detective Conan Movie 23: The Fist of Blue Sapphire',
 "Magical Girl Lyrical Nanoha: The Movie 2nd A's",
 'Blue Spring Ride: Page.13',
 'Thunderbolt Fantasy Movie 2: Bewitching Melody of the West',
 'Major: Message',
 'The Tale of the Princess Kaguya',
 'One Piece Film: Gold',
 'Broken Blade Movie 4: The Land of Calamity',
 'Evangelion: 1.0 You Are (Not) Alone',
 'Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero',
 'Gintama: Jump Festa 2015',
 'KonoSuba – God’s blessing on this wonderful world! 2 OVA',
 "JoJo's Bizarre Adventure: Phantom Blood",
 'Puella Magi Madoka Magica the Movie Part 1: Beginnings',
 'The Garden of Words',
 'Legend of the Galactic Heroes: Overture to a New War',
 'Saekano: How to Raise a Boring Girlfriend Fine',
 'The Garden of Sinners Movie 4: Garan-no-Dou. (The Hollow Shrine)',
 'Ghost in the Shell',
 'The Secret World of Arrietty',
 'Ghost in the Shell: Stand Alone Complex - Individual Eleven',
 'Bungou Stray Dogs Movie: Dead Apple',
 'Detective Conan Movie 8: Magician of the Silver Sky',
 'Legend of the Galactic Heroes: Die Neue These Second 1',
 'Broken Blade Movie 5: The Gap Between Life & Death',
 'Hajime no Ippo: The Fighting! Special',
 'Kamisama Kiss OVA',
 'Detective Conan Movie 5: Countdown to Heaven',
 'Made in Abyss: Tabidachi no Yoake',
 "Broken Blade Movie 3: Scars from an Assassin's Blade",
 'Gintama: Dai Hanseikai',
 'Non Non Biyori Movie: Vacation',
 'One-Punch Man: Road to Hero',
 'The Garden of Sinners: Recalled Out Summer',
 'Code Geass: Lelouch of the Rebellion I - Initiation',
 'Sekai-ichi Hatsukoi: Yokozawa Takafumi no Baai',
 'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
 'Girls und Panzer: Saishuushou 2',
 'Wotakoi: Love is Hard for Otaku - Youth',
 'The Anthem of the Heart',
 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
 'Detective Conan Movie 3: The Last Magician of the Century',
 "One Piece 3D2Y: Overcoming Ace's Death! Luffy's Pledge to His Friends!",
 'Night is Short, Walk On Girl',
 'The Wind Rises',
 'Free! Eternal Summer - Forbidden All Hard!',
 'Junjou Romantica OVA 2',
 'Food Wars! Toutsuki Juukketsu',
 'High Speed! -Free! Starting Days-',
 'Gintama: Jump Festa 2005',
 'The Garden of Sinners Movie 2: ...And Nothing Heart. (Murder Speculation Part A)',
 'Clannad: Another World, Tomoyo Chapter',
 "Gurren Lagann Movie 1: Childhood's End",
 'Haikyuu!! vs. "Akaten"',
 'Ghost in the Shell 2.0',
 'Major Movie: Yuujou no Winning Shot',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Initial D Legend 3: Dream',
 'Ne Zha',
 'Spice and Wolf II OVA',
 'From Up On Poppy Hill',
 'Free! -Take Your Marks-',
 'One Piece: Strong World - Episode 0',
 "Detective Conan Movie 10: The Private Eyes' Requiem",
 'Lupin III vs Detective Conan: The Movie',
 'Broken Blade Movie 2: The Path of Separation',
 'Death Billiards',
 'Snow White with the Red Hair OVA',
 'Legend of the Galactic Heroes: My Conquest is the Sea of Stars',
 'Broken Blade Movie 6: Fortress of Lamentation',
 'My Teen Romantic Comedy SNAFU TOO! OVA',
 "Kuroko's Basketball: Tip Off",
 'Initial D Legend 2: Racer',
 'The Labyrinth of Grisaia',
 'Yona of the Dawn OVA',
 'Initial D Legend 1: Awakening',
 'Detective Conan Movie 4: Captured In her Eyes',
 'Berserk: Golden Age Arc I - The Egg of the King',
 'Detective Conan Movie 22: Zero no Shikkounin',
 'Paprika',
 'Tamayura: Sotsugyou Shashin Movie 4 - Ashita',
 "Okko's Inn Movie",
 'Initial D Third Stage',
 'The Disappearance of Conan Edogawa: The Worst Two Days in History',
 'Psycho-Pass SS: Case. 3 - Onshuu no Kanata ni',
 'Overlord: Shikkoku no Senshi',
 'Sket Dance OVA',
 'Psycho-Pass: The Movie',
 'Haikyuu!! Movie 1: Owari to Hajimari',
 'Interstella 5555 - The 5tory of the 5ecret 5tar 5ystem',
 'Kase-san and Morning Glories',
 'Saezuru Tori wa Habatakanai: The Clouds Gather',
 'Detective Conan Movie 16: The Eleventh Striker',
 'The Seven Deadly Sins Movie: Prisoners of the Sky',
 'Broken Blade Movie 1: The Time of Awakening',
 'Overlord: Fushisha no Ou',
 "Natsume's Book of Friends: Nyanko-sensei & The First Errand",
 'Kishibe Rohan wa Ugokanai: Zange-shitsu',
 'Neon Genesis Evangelion: The End of Evangelion',
 'One Piece: Episode of East Blue',
 'Perfect Blue',
 'Aria the Origination: That Secret Little Place...',
 'Sekai-ichi Hatsukoi: Valentine-hen',
 'One Piece: Episode of Sabo',
 'The Cat Returns',
 'Girls und Panzer: Saishuushou',
 'Liz and the Blue Bird',
 'The Last: Naruto the Movie',
 "xxxHOLiC Movie: A Midsummer Night's Dream",
 'Magical Girl Lyrical Nanoha The MOVIE 1st',
 'Tamako Love Story',
 'Yuri!!! on Ice: Welcome to The Madness',
 'Hanasaku Iroha: Home Sweet Home',
 'Lupin III: Castle Of Cagliostro',
 'Hellsing Ultimate: Digest for Freaks',
 'Mobile Suit Gundam Wing: Endless Waltz Movie',
 'Code Geass: Lelouch of the Rebellion II - Transgression',
 'Stand by Me Doraemon',
 "Miss Kobayashi's Dragon Maid: Valentines and Hot Springs! (Please Don't Get Your Hopes Up)",
 'Mobile Suit Gundam: Thunderbolt - December Sky',
 'Sword Art Online Movie: Ordinal Scale',
 'Kikuo: Aishite Aishite Aishite',
 'Persona 3 The Movie 4: Winter of Rebirth',
 'Anohana: The Flower We Saw That Day Movie',
 'Out of Sight',
 'Transformers: The Movie',
 'Code Geass: Lelouch of the Rebellion R2 Special Edition - Zero Requiem',
 'Detective Conan Movie 1: The Time Bombed Skyscraper',
 'Final Fantasy VII: Advent Children',
 'Ponyo on the Cliff by the Sea',
 'Haikyuu!! Movie 2: Shousha to Haisha',
 'Detective Conan Movie 2: The Fourteenth Target',
 'The Garden of Sinners Movie 1: Thanatos. (Overlooking View)',
 'Clannad: Another World, Kyou Chapter',
 'Hakuouki Movie 2: Warrior Spirit of the Blue Sky',
 'Cardcaptor Sakura: The Movie 2: The Sealed Card',
 'Nodame Cantabile: Finale Special',
 'Aria the OVA: Arietta',
 'Hikaru no Go: Journey to the North Star Cup',
 'Fate/Kaleid Liner Prisma Illya Movie: Vow in the Snow',
 'Planetarian Movie: Hoshi no Hito',
 'Little Witch Academia',
 'Re:ZERO -Starting Life in Another World- The Frozen Bonds',
 "Kino's Journey: Life Goes On",
 'Full Metal Panic! The Second Raid: A Relatively Leisurely Day in the Life of a Fleet Captain',
 'Detective Conan Movie 21: Kara Kurenai no Love Letter',
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Date a Live: Encore OVA',
 'Detective Conan Movie 12: Full Score of Fear',
 "Lupin III: Goemon's Blood Spray",
 'School Babysitters Special',
 'Lucky Star OVA',
 'Durarara!! X2: My Heart Is in the Pattern of a Hot Pot',
 'Vampire Hunter D: Bloodlust',
 'Hakuouki Movie 1: Wild Dance of Kyoto',
 'Detective Conan Movie 17: Zekkai no Private Eye',
 'Bungou Stray Dogs: Walking Alone',
 "Hozuki's Coolheadedness OVA 2",
 "Kuroko's Basketball Movie 3: Winter Cup Highlights -Crossing the Door-",
 'Fairy Tail Movie 2: Dragon Cry',
 'Love Live! The School Idol Movie',
 'Ride Your Wave',
 'Thunderbolt Fantasy Movie: The Sword of Life and Death',
 'Hidamari Sketch x 365 EX',
 'Haikyuu!! Lev Kenzan!',
 'Drifters: Special Edition',
 'Porco Rosso',
 'Macross Frontier Movie 2: Sayonara no Tsubasa',
 'Little Witch Academia: The Enchanted Parade',
 'Detective Conan OVA 10: Kid in Trap Island',
 'Assassination Classroom: Jump Festa 2013 Special',
 'Your lie in April: Moments',
 "Kuroko's Basketball: Let's Do That Again",
 'Digimon Adventure Tri. Movie 3: Confession',
 'Towa no Quon 6: Towa no Quon',
 'Detective Conan OVA 9: The Stranger of 10 Years',
 'Minami: Kawaki wo Ameku',
 'Space Battleship Yamato 2199: Hoshi-Meguru Hakobune',
 'The Garden of Sinners Movie 6: Fairy Tale. (Oblivion Recording)',
 'Eden of The East Movie I: The King of Eden',
 "Lupin III: Jigen's Gravestone",
 'Seitokai Yakuindomo Movie',
 'Blue Exorcist Movie',
 'Tiger & Bunny The Movie: The Rising',
 'Cardcaptor Sakura: Clear Card Prologue - Sakura and the Two Bears',
 'Osomatsu-san The Movie',
 'Free! -Timeless Medley- The Promise',
 'Naruto Shippuden Movie 6: Road to Ninja',
 'My Hero Academia - All Might: Rising The Animation',
 'Eden of The East Movie II: Paradise Lost',
 'Code Geass: Lelouch of the Rebellion Special Edition - Black Rebellion',
 'InuYasha: Kuroi Tessaiga',
 'Detective Conan Movie 9: Strategy Above the Depths',
 'Detective Conan Movie 7: Crossroad in the Ancient Capital',
 'K: Missing Kings',
 'Towa no Quon 4: Guren no Shoushin',
 'Attack on Titan Movie 3: The Roar of Awakening',
 'Junjou Romantica OVA',
 'Colorful (2010)',
 'Free! Dive to the Future: Build-Up of Early Spring!',
 'The Dog of Flanders Movie',
 'KonoSuba – God’s blessing on this wonderful world! OVA',
 'Lupin III Special 21: Lupin III vs Detective Conan',
 'Akira',
 'Free! -Timeless Medley- The Bond',
 'The Garden of Sinners Remix: Gate of Seventh Heaven',
 'Recollections of a Certain Pilot',
 'Fullmetal Alchemist The Movie: Conqueror of Shamballa',
 "Goblin Slayer: Goblin's Crown",
 'Is It Wrong to Try to Pick Up Girls in a Dungeon? Movie: Arrow of the Orion',
 'Saint Young Men Movie',
 'Food Wars! Shokugeki no Souma OVA',
 'Tales of Vesperia ~The First Strike~',
 'Free! Road to the World - Yume',
 'K-On! Live House!',
 "Interviews with Monster Girls: The Demi-chans' Summer Break",
 'K-On!!: Plan!',
 "Kino's Journey: Byouki no Kuni -For You-",
 "Giovanni's Island",
 'Rurouni Kenshin: Special Techniques',
 'Yuru Yuri Nachu Yachumi!',
 "Kuroko's Basketball Movie 2: Winter Cup Highlights -Beyond the Tears-",
 'Hello World',
 "Kuroko's Basketball OVA",
 'Piano no Mori',
 'Lupin III: The First',
 'Towa no Quon 5: Souzetsu no Raifuku',
 'Fate/stay night: Unlimited Blade Works Movie',
 'Kill La Kill Special',
 'The Kawai Complex Guide to Manors and Hostel Behavior: First Time',
 'Yowamushi Pedal The Movie',
 'Space Brothers: Number Zero',
 'Non Non Biyori Repeat OVA',
 'Angel Beats! Stairway to Heaven',
 "Persona 3 The Movie 2: Midsummer Knight's Dream",
 'The Irregular at Magic High School Movie: The Girl Who Summons the Stars',
 'Kingsglaive: Final Fantasy XV',
 'Digimon Adventure Tri. Movie 2: Determination',
 'Tekkon Kinkreet',
 'Boruto: Naruto the Movie',
 'Bleach Movie 4: Hell Verse',
 'One Piece: Episode of Luffy - Hand Island no Bouken',
 'The Tibetan Dog',
 'Noblesse: Awakening',
 'Mob Psycho 100 II: The First Spirits and Such Company Trip - A Journey that Mends the Heart and Heals the Soul',
 'Kabaneri of the Iron Fortress Movie: The Battle of Unato',
 'Barefoot Gen',
 'Inu X Boku Secret Service Special',
 'Persona 3 The Movie 1: Spring of Birth',
 'One Piece Special: Heart of Gold',
 "Danganronpa 3: The End of Hope's Peak Academy- Hope Arc",
 'Psycho-Pass SS: Case. 2 - First Guardian',
 'Ghost in the Shell 2: Innocence',
 'K: Seven Stories Movie 5 - Memory of Red ~BURN~',
 'L.O.R.D: Legend of Ravaging Dynasties',
 'Food Wars! The Third Plate: Erina no Shin Seikatsu',
 'Re:ZERO -Starting Life in Another World- Memory Snow',
 'Macross Frontier Movie 1: Itsuwari no Utahime',
 'Rurouni Kenshin Movie',
 '5 Centimeters per Second',
 'Beyond the Boundary: Shinonome',
 'Nodame Cantabile OVA 2',
 'Children Who Chase Lost Voices',
 'Magical Girl Lyrical Nanoha THE MOVIE 3rd Reflection',
 'Kishibe Rohan wa Ugokanai: Mutsukabezaka',
 'Penguin Highway',
 'Durarara!! X2 The Third Arc: Dufufufu!',
 'Towa no Quon 3: Mugen no Renza',
 "Kino's Journey: Tower Country",
 'Ojii-san no Lamp',
 'Death Note Rewrite 1: Visions of a God',
 "Beyond the Boundary Movie: I'll Be Here - Past",
 'A Letter to Momo',
 'Madangeul Naon Amtak',
 "Kuroko's Basketball Movie 1: Winter Cup Highlights -Shadow and Light-",
 'Food Wars! Jump Festa 2016 Special',
 'Detective Conan Movie 09: Promo Special',
 'The Place Promised in Our Early Days',
 'Comedy',
 'Mobile Suit Gundam 00 Special Edition II: End of World',
 'Haikara-San: Here Comes Miss Modern Part 1',
 'Mobile Suit Gundam 00 Special Edition I: Celestial Being',
 'Yu-Gi-Oh! Movie 4: The Dark Side of Dimensions',
 'Mobile Suit Gundam 00 Special Edition III: Return the World',
 'Hori-san to Miyamura-kun (2018)',
 'Persona 4 the Animation: The Factor of Hope',
 'A Certain Magical Index Movie: The Miracle of Endymion',
 'Fairy Tail Movie 1: Phoenix Priestess',
 'Girls und Panzer: This is the Real Anzio Battle!',
 'Macross: Do You Remember Love',
 'One Piece Movie 4: Dead End Adventure',
 'Full Metal Panic! The Second Raid: Episode 00',
 'My Hero Academia: Training of the Dead',
 'Kill Bill Chapter 3: The Origin of O-Ren',
 'Persona 3 The Movie 3: Falling Down',
 'Professor Layton and the Eternal Diva',
 'Mardock Scramble: The First Compression',
 'Heaven’s Lost Property The Movie: The Angeloid of Clockwork',
 'Garo Movie: Divine Flame',
 'Tamayura: Sotsugyou Shashin Movie 3 - Akogare',
 'Mitsudomoe Special',
 'Big Fish & Begonia',
 'Arashi no Yoru ni',
 'Magical Girl Lyrical Nanoha: Detonation',
 'Strike Witches Movie',
 'Ajin Movie 3: Shougeki',
 'Dragon Ball Z Movie 14: Battle of Gods',
 'Minami-ke Betsubara',
 'Digimon Adventure Tri. Movie 1: Reunion',
 "Death Note Rewrite 2: L's Successors",
 'Magical Sisters Yoyo & Nene',
 'Banner of the Stars: Tokubetsu Hen',
 'Un-Go: Chapter of Inga',
 'Ajin Movie 1: Shoudou',
 'Orange -Mirai-',
 'Digimon Adventure Movie: Last Evolution Kizuna',
 'Eden of the East Compilation: Air Communication',
 'Sound! Euphonium Movie 3: Our Promise - A Brand New Day',
 'Ranma 1/2 Akumu! Shunmin Kou',
 'Durarara!! X2 The Second Arc: Onoroke Chakapoko',
 'Tenchi Muyo! Ryo Ohki: Final Confrontations',
 'Mardock Scramble: The Third Exhaust',
 'Bokura no Nanokakan Sensou',
 'Initial D Battle Stage 2',
 'Macross Frontier Deculture Edition',
 'Evangelion: 3.0 You Can (Not) Redo',
 'Kaleido Star: Legend of Phoenix ~Layla Hamilton Story~',
 'The Garden of Sinners: Recalled Out Summer - Extra Chorus',
 'Is this a Zombie? Of the Dead: Yes, This Suits Me Just Fine',
 'Detective Conan Movie 11: Jolly Roger in the Deep Azure',
 'Sengoku Basara: Samurai Kings Movie - The Last Party',
 'InuYasha The Movie 3: Swords of an Honorable Ruler',
 'Tamayura: Sotsugyou Shashin Movie 2 - Hibiki',
 'Darker than Black: Beneath Cherry Blossoms in Full Bloom...',
 'A Certain Scientific Railgun OVA',
 "Mary and the Witch's Flower",
 'Macross Plus Movie Edition',
 'Detective Conan Magic File 4: Osaka Okonomiyaki Odyssey',
 'Love, Chunibyo & Other Delusions!: Sparkling... Slapstick Noel',
 'Naruto Shippuden Movie 5: Blood Prison',
 'Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou Part 2 - Tamashii',
 'Ghost in the Shell: The New Movie',
 'Nodame Cantabile OVA',
 'Recovery of an MMO Junkie Special',
 'Toradora! The True Meaning of Bento',
 'Yowamushi Pedal: Spare Bike',
 'Persona 4 The Animation: No One is Alone',
 'Love Stage!! OVA',
 'Asobi Asobase OVA',
 'Urusei Yatsura Movie 2: Beautiful Dreamer',
 'Linkin Park: Breaking the Habit',
 'Detective Conan Magic File 2: Kudou Shinichi - The Case of the Mysterious Wall and the Black Lab',
 'Chibi Maruko-chan: Watashi no Suki na Uta',
 'Bleach Movie 3: Fade to Black',
 'Detective Conan OVA 4: Conan and Kid and Crystal Mother',
 'Mind Game',
 "Servamp: Hai ni Mamireta Shoukei - All the world's a stage",
 'Furiko',
 'My Hero Academia: Jump Festa 2016 Special',
 "Angel Beats! Hell's Kitchen",
 "Mobile Suit Gundam: Char's Counterattack",
 "Heaven's Lost Property: Project Pink",
 'K: Seven Stories Movie 4 - Lost Small World ~Outside the Cage~',
 'One Piece Movie 6: Baron Omatsuri and the Secret Island',
 'My Teen Romantic Comedy SNAFU OVA',
 'Boruto: Naruto the Movie - The Day Naruto Became Hokage',
 'Meiji Tokyo Renka Movie: Yumihari no Serenade',
 'Towa no Quon 1: Utakata no Kaben',
 'Mardock Scramble: The Second Combustion',
 'Ajin Movie 2: Shoutotsu',
 'Lu Over the Wall',
 'Cells at Work! The Common Cold',

In [21]:
# unique media types
data['mediaType'].unique()

<ArrowStringArray>
[         'TV',       'Movie',         'Web',  'TV Special',         'OVA',
  'is_missing', 'DVD Special',       'Other', 'Music Video']
Length: 9, dtype: str

In [22]:
# which title are bassed on which mediatype or how many titles for each mediatype
data.groupby('mediaType')['title'].count()

mediaType
DVD Special     803
Movie          1928
Music Video    1290
OVA            1770
Other           580
TV             3993
TV Special      504
Web            1170
is_missing       63
Name: title, dtype: int64

In [23]:
data['mediaType'].value_counts()

mediaType
TV             3993
Movie          1928
OVA            1770
Music Video    1290
Web            1170
DVD Special     803
Other           580
TV Special      504
is_missing       63
Name: count, dtype: int64

In [24]:
#data columns
data.columns

Index(['title', 'description', 'mediaType', 'eps', 'duration', 'ongoing',
       'sznOfRelease', 'years_running', 'studio_primary', 'studios_colab',
       'contentWarn', 'watched', 'watching', 'wantWatch', 'dropped', 'rating',
       'votes', 'tag_Based_on_a_Manga', 'tag_Comedy', 'tag_Action',
       'tag_Fantasy', 'tag_Sci_Fi', 'tag_Shounen', 'tag_Original_Work',
       'tag_Non_Human_Protagonists', 'tag_Drama', 'tag_Adventure',
       'tag_Family_Friendly', 'tag_Short_Episodes', 'tag_School_Life',
       'tag_Romance', 'tag_Shorts', 'tag_Slice_of_Life', 'tag_Seinen',
       'tag_Supernatural', 'tag_Magic', 'tag_Animal_Protagonists', 'tag_Ecchi',
       'tag_Mecha', 'tag_Based_on_a_Light_Novel', 'tag_CG_Animation',
       'tag_Superpowers', 'tag_Others', 'tag_missing'],
      dtype='str')

In [26]:
data['studio_primary'].value_counts()

studio_primary
Others                  4340
is_missing              3208
Toei Animation           636
Sunrise                  430
J.C. Staff               341
MADHOUSE                 337
TMS Entertainment        317
Production I.G           271
Studio Deen              260
Studio Pierrot           221
OLM                      210
A-1 Pictures             194
AIC                      167
Shin-Ei Animation        164
Nippon Animation         145
Tatsunoko Production     144
DLE                      130
GONZO                    124
Bones                    121
Shaft                    118
XEBEC                    117
Kyoto Animation          106
Name: count, dtype: int64

In [28]:
data['sznOfRelease'].value_counts()

sznOfRelease
is_missing    8554
Spring        1135
Fall          1011
Winter         717
Summer         684
Name: count, dtype: int64

In [29]:
#retrive the data of sznOfRelease in spring and studio_primary sunrise
data[(data['sznOfRelease'] == 'Spring') & (data['studio_primary'] == 'Sunrise')]

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
12,Code Geass: Lelouch of the Rebellion R2,Area 11 is still under Britannian rule and the...,TV,25,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,1,0,0
21,Gintama',"Gintoki Sakata, Kagura, and Shinpachi Shimura ...",TV,51,NaN,False,Spring,1,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
62,Cowboy Bebop,Follow interstellar bounty hunters Spike Spieg...,TV,26,NaN,False,Spring,1,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
306,Gintama,"In Gintoki's Japan, the arrival of the various...",TV,201,NaN,False,Spring,4,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
522,Mobile Suit Gundam: The Origin - Advent of the...,"The tragic story of Char Aznable, the ace pilo...",TV,13,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
730,Tiger & Bunny,"In Sternbuild City, corporate logos not only c...",TV,25,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,1,0,0
867,Love Live! School Idol Project 2,With Otonokizaka Academy saved by Honoka Kōsak...,TV,13,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
1201,Banner of the Stars,Three years have passed since the Four Nations...,TV,13,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
1506,GaoGaiGar FINAL Grand Glorious Gathering,With the 31 Primevals defeated and their sinis...,TV,12,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
1560,The Vision of Escaflowne,"Hitomi was just a normal high school girl, unt...",TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
1675,Accel World,In a world where everyone connects to an onlin...,TV,24,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,1,0,0,0,0
1752,Sgt. Frog,As the mighty star fleet of the planet Keron p...,TV,358,NaN,False,Spring,7,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
2215,Zegapain,Sogoru Kyo is a normal high school student wit...,TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
2246,Mobile Suit Gundam Unicorn RE:0096,U.C. 0096... The manufacturing colony Industri...,TV,22,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
2292,Phi Brain: Kami no Puzzle 2,"The battle with POG is over, but Kaito's deter...",TV,25,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
2294,"Wave, Listen to Me!","The stage is Sapporo, Hokkaido. One night, our...",TV,11,NaN,True,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
2435,Isekai Izakaya: Japanese Food From Another World,On a deserted street somewhere in Kyoto reside...,TV,24,15.0,False,Spring,0,Sunrise,0,...,0,0,0,0,0,1,0,0,0,0
2514,Valvrave the Liberator,"In the future, Earth is split into three facti...",TV,12,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
2728,Turn A Gundam,"The year is 2345 Correct Century, and in the a...",TV,50,NaN,False,Spring,1,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
3710,Zone of the Enders: Dolores,The hostility between Earth and Mars has grown...,TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
4248,Natsuiro Kiseki,"Natsumi, Saki, Yuka, and Ringo are best friend...",TV,12,NaN,False,Spring,0,Sunrise,0,...,0,1,0,0,0,0,0,0,0,0
4304,Battle Spirits: Sword Eyes Gekitouden,NaN,TV,21,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,1,0
4789,Ginga Hyouryuu Vifam 13,NaN,TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
4903,Gundam Build Divers,Gunpla Battle Nexus Online (GBN) is a new netw...,TV,25,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
5945,The iDOLM@STER: Xenoglossia,"Much to her delight and surprise, Haruka was s...",TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
5990,Betterman,After a random encounter with his childhood fr...,TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
6639,Keroro,"Sergeant Keroro, who is ”58th Planet of the Ga...",TV,23,3.0,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
6720,Wild Knights Gulkeeva,"Shinjou Touya, a seventeen-year-old student, l...",TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,1,0
7667,Sentimental Journey,"In twelve cities, twelve different girls will ...",TV,12,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
7826,Angel Links,Sixteen-year-old Meifon Li runs the security c...,TV,13,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,1,0,0,0,0
8442,SD Gundam Sangokuden Brave Battle Warriors,NaN,TV,51,12.0,False,Spring,1,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
8802,Brain Powerd,"In a possible future, mysterious devices calle...",TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0
9097,DT Eightron,NaN,TV,26,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
10444,Mobile Suit Gundam: Twilight Axis,"Universal Century 0096, a few months after the...",Web,6,3.0,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,0,0,0

In [37]:
#find which movie is most watched in the dataset
data.sort_values(by='watched', ascending=False)[['title', 'watched']].head(1)

         title   watched
97  Death Note  161567.0

In [39]:
# figure how many title watched by more than 100/ 100?
data[data['watched'] >= 100].shape[0]

8114

In [40]:
#watched > 100 and rating > 3.5
data[(data['watched'] > 100) & (data['rating'] > 3.5)].shape[0]

3363